### ISSUE TITLE
Dollar sign and quotes are escaped in minted blocks

### ISSUE THREAD

**Issue by abdelrahman-elkady** [area/language-latex#75]
I am using [minted](http://mirror.unl.edu/ctan/macros/latex/contrib/minted/minted.pdf) for code highlighting in latex, normally, all symbols inside a code block wouldn't be escaped

The current version breaks the highlight when quotes or a dollar sign is passed within the block

![screenshot from 2016-05-13 19 43 45](https://cloud.githubusercontent.com/assets/10640699/15256718/19f36bf2-1943-11e6-9cf7-a0781226eca6.png)

**Comment by qwemaze** [comment]
got into same problem
i've made a fork without quotes highlight, and also recommend you to use `\inputminted[<options>]{<languaage>}{<filepath>}` load src files externally in `minted`

**Comment by yudai-nkt** [comment]
Hi @abdelrahman-elkady,

Since the original maintainers are somehow inactive on this package for almost one year, I am now making a new one ([yudai-nkt/language-tex](https://github.com/yudai-nkt/language-tex)) based on the clone of this repo. Your problem is fixed and this is how your example looks with my package.

![2016-07-16 19 29 19](https://cloud.githubusercontent.com/assets/13291527/16894287/9886515c-4b8c-11e6-9088-344f3118ab11.png)

I'm happy if you get interested in this package and give some feedback.

**Comment by Berkmann18** [comment]
I see that this has been apparently fixed but it's still a problem (a tex code readers/parsers I tried are thrown off by this).
